## Array Aggregation Methods

In [4]:
import numpy as np

array.sum() array.mean() array.max() array.min()

In [5]:
sales = [0, 5, 155, 0, 518], [0, 1827, 616, 317, 325]

sales_array = np.array(sales)

sales_array

array([[   0,    5,  155,    0,  518],
       [   0, 1827,  616,  317,  325]])

In [6]:
print(sales_array.sum())
print(sales_array.mean())
print(sales_array.min())
print(sales_array.max())

3763
376.3
0
1827


In [7]:
sales_array.sum(axis=0)

array([   0, 1832,  771,  317,  843])

In [8]:
sales_array.sum(axis=1)

array([ 678, 3085])

In [9]:
rng = np.random.default_rng(616)

price = (rng.random(10) * 10).round(2)

price

array([3.97, 8.66, 4.6 , 3.06, 5.74, 0.89, 8.82, 7.32, 7.32, 5.62])

In [10]:
invetory = rng.integers(0, 100, 10)

invetory

array([80, 33, 60,  6, 31, 35, 16, 20, 29, 43], dtype=int64)

In [11]:
invetory.mean()

35.3

In [12]:
invetory.sum()

353

In [13]:
invetory.min()

6

In [14]:
invetory.std()

20.48438429633656

In [15]:
round((price * invetory).sum(), 2)

1848.29

In [16]:
price_2d = price.reshape(5, 2)

price_2d

array([[3.97, 8.66],
       [4.6 , 3.06],
       [5.74, 0.89],
       [8.82, 7.32],
       [7.32, 5.62]])

In [17]:
price_2d.sum(axis=1)

array([12.63,  7.66,  6.63, 16.14, 12.94])

## Array functions

In [18]:
sales_array

array([[   0,    5,  155,    0,  518],
       [   0, 1827,  616,  317,  325]])

In [19]:
np.median(sales_array)

236.0

In [26]:
np.percentile(sales_array, 90) # np.percentile(array, n) n is equal to the percentile we want returned. 25th, 50th, 75th percentile, etc...

737.0999999999996

In [27]:
np.unique(sales_array) # removes duplicates in an array

array([   0,    5,  155,  317,  325,  518,  616, 1827])

In [28]:
np.sqrt(sales_array)

array([[ 0.        ,  2.23606798, 12.4498996 ,  0.        , 22.75961335],
       [ 0.        , 42.74342055, 24.81934729, 17.80449381, 18.02775638]])

In [33]:
new_price = np.array([2.6, 7.2, 6.92, 3.88, 0.78, 2.67, 8.87, 0.23, 5.23, 6.3])

new_price

array([2.6 , 7.2 , 6.92, 3.88, 0.78, 2.67, 8.87, 0.23, 5.23, 6.3 ])

In [34]:
new_invetory = np.array([79, 22, 20, 48, 8, 76, 12, 16, 5, 64])
new_invetory

array([79, 22, 20, 48,  8, 76, 12, 16,  5, 64])

In [35]:
product_value = new_price * new_invetory

product_value

array([205.4 , 158.4 , 138.4 , 186.24,   6.24, 202.92, 106.44,   3.68,
        26.15, 403.2 ])

In [39]:
product_value.sort()
product_value

array([  3.68,   6.24,  26.15, 106.44, 138.4 , 158.4 , 186.24, 202.92,
       205.4 , 403.2 ])

In [36]:
reshaped_product_value = product_value.reshape(2, 5)

reshaped_product_value

array([[205.4 , 158.4 , 138.4 , 186.24,   6.24],
       [202.92, 106.44,   3.68,  26.15, 403.2 ]])

In [37]:
# Takes the center two values of this array, adds them, then divides by 2 to give the median. 
# If the center value of the array was odd, the median would be that number

np.median(reshaped_product_value)

148.4

In [44]:
np.percentile(reshaped_product_value, 90)

225.17999999999992

In [45]:
np.sqrt(reshaped_product_value)

array([[ 1.91833261,  2.4979992 ,  5.11370707, 10.3169763 , 11.76435294],
       [12.58570618, 13.64697769, 14.24499912, 14.33178286, 20.07984064]])

In [46]:
np.unique(reshaped_product_value)

array([  3.68,   6.24,  26.15, 106.44, 138.4 , 158.4 , 186.24, 202.92,
       205.4 , 403.2 ])