## <center> Broadcasting </center>

### Lets you perform  vectorized operations with arrays of different sizes, where NumPy will expand the smaller array 'fit' the larger one

In [5]:
import numpy as np

In [6]:
test_array = np.array([[1, 2, 3], [1, 2, 3], [1, 2, 3]])

test_array

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [7]:
test_array + 1 # One is added to every element in this array through the NumPy broadcasting 

array([[2, 3, 4],
       [2, 3, 4],
       [2, 3, 4]])

In [9]:
test_array + np.array([3, 2, 1]) # Add each element of np.array to test_array array element and its column

array([[4, 4, 4],
       [4, 4, 4],
       [4, 4, 4]])

In [11]:
test_array + np.array([3, 2, 1]).reshape(3, 1) # Adds the elements of test_array to each row of one column of np.array()

array([[4, 5, 6],
       [3, 4, 5],
       [2, 3, 4]])

#### <center>what happens if we don't have a matching dimension </center>

In [12]:
test_array + np.array([2, 1])

ValueError: operands could not be broadcast together with shapes (3,3) (2,) 

numpy and pandas can't broadcast to dimensions with a len

In [13]:
test_array[0, :] + test_array[:, 1].reshape(3, 1)

array([[3, 4, 5],
       [3, 4, 5],
       [3, 4, 5]])