## python indexing and slicing
array[index] - indexing to access a single element (0-indexed)

array[start:stop:step size] - slicing to access a series of elements (stop is not inclusive)

## indexing and slicing 2 dem arrays require coordinates, or, an extra index or slice

array[row index, column index] - indexing to access a single element (0-indexed)

array[start:stop:step size, start:stop:step size] - slicing to access a series of elements

In [1]:
import numpy as np

In [2]:
integer_array = np.arange(12)

In [3]:
integer_array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [4]:
integer_array[0] #index first element

0

In [18]:
integer_array[1] # index second element

1

In [16]:
integer_array[11] # index last elemting by absolute index value

11

In [7]:
integer_array[-1] # index last value by using negative one to jump to the end of the list

11

In [8]:
integer_array[:5] # slicing for the first 5 elements by adding a stop value at the 5th element. 0-indexed so stops at 4 (not inclusive)

array([0, 1, 2, 3, 4])

In [9]:
# slicing all the elements after the fith element with no stop. 
# Since no stop it will return all elements after the 5th untill it can't any

integer_array[5:]

array([ 5,  6,  7,  8,  9, 10, 11])

In [19]:
integer_array[::2] # step of to. No start and stop so will return all elements in step of 2

array([ 0,  2,  4,  6,  8, 10])

In [33]:
new_array = integer_array.reshape(3, 4) # reshape to a multidemsional array(MDA)
new_array

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [34]:
new_array[:, :] # no instruction. Calls entire array

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [35]:
new_array[1:, :] # calls the second element in the MDA. Meaning it calls the second row onwards but excludes the first element or row in the index

array([[ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [36]:
# returns only the last column. 3 is in the cloumn portion of the slice that follows the comma.
# Also returns as 1 dem array because we only have one column

new_array[:, 3]

array([ 3,  7, 11])

In [37]:
new_array[:, 1:3] # this will exclude the final column because stop is not inclusive

array([[ 1,  2],
       [ 5,  6],
       [ 9, 10]])

In [40]:
new_array[2, 1]

9