## Sorting Arrays

In [ ]:
import numpy as np

In [12]:
sales = [0, 5, 155, 0, 518], [0, 1827, 616, 317, 325]

sales_array = np.array(sales)

sales_array

array([[   0,    5,  155,    0,  518],
       [   0, 1827,  616,  317,  325]])

In [ ]:
sales_array.sort() # by default sorts by axis=1, which sorts a two demensional array row by row
sales_array

In [13]:
sales_array.sort(axis=0) # axis=0 will sort by columns

# array([[   0,    5,  155,    0,  325],          # if this output does not appear then the previous sort axis=1 is in memory
#        [   0, 1827,  616,  317,  518]])

array([[   0,    5,  155,    0,  325],
       [   0, 1827,  616,  317,  518]])

In [14]:
new_price = np.array([2.6, 7.2, 6.92, 3.88, 0.78, 2.67, 8.87, 0.23, 5.23, 6.3])

new_invetory = np.array([79, 22, 20, 48, 8, 76, 12, 16, 5, 64])

product_value = new_price * new_invetory

product_value

array([205.4 , 158.4 , 138.4 , 186.24,   6.24, 202.92, 106.44,   3.68,
        26.15, 403.2 ])

In [15]:
np.sort(product_value) # this is a copy of the array sorted. 'product_value' is still in place with 205.4 in index 0

array([  3.68,   6.24,  26.15, 106.44, 138.4 , 158.4 , 186.24, 202.92,
       205.4 , 403.2 ])

In [17]:
product_value.sort() # now the value is sorted in memory. 
product_value

array([  3.68,   6.24,  26.15, 106.44, 138.4 , 158.4 , 186.24, 202.92,
       205.4 , 403.2 ])

In [18]:
product_value[0] # after sorting the value commited to memory this would call the 0 index which is not the minimum value

3.68

In [19]:
product_value[-1] # max value would be the last index value

403.2

In [21]:
product_value[::-1] # reverse sequence negative slice. returns array in reverse order

array([403.2 , 205.4 , 202.92, 186.24, 158.4 , 138.4 , 106.44,  26.15,
         6.24,   3.68])